### PR TITLE
Update CSS file name for BetterDiscord theme

### PR DESCRIPTION
**Pull request by speelbarrow**

### CODE REVIEW

**Comment by danielbayley** [comment]
@speelbarrow Thanks!

**Comment by speelbarrow** [comment]
@danielbayley  hey, it seems like this commit didn't get merged into `main` properly. If you look on the `main` branch currently, you can see that the change this commit made isn't there. Any idea what's going on there?

**Comment by danielbayley** [comment]
> @danielbayley hey, it seems like this commit didn't get merged into `main` properly. If you look on the `main` branch currently, you can see that the change this commit made isn't there. Any idea what's going on there?

@speelbarrow Not sure what happened there! If you open another PR, I will `merge` ASAP…

**Comment by speelbarrow** [comment]
@danielbayley thanks for the quick reply! I've opened another PR #13.

**Pull request merged**
